apiVersion: v1
kind: Service
metadata:
  name: scaletest-service
spec:
  type: NodePort
  selector:
    app: scaletest-app
  ports:
    - protocol: TCP
      port: 8080        # Порт сервиса внутри кластера
      targetPort: 8080  # Порт контейнера
